### ISSUE TITLE
I would love contribute my solutions as well, 

### ISSUE THREAD

**Issue by Phakeme** [pinglu85/algoExpert#1]
I use this repo every day to study and practice AlgoExpert challenges,
How do I contribute my solutions to help others who are practicing AlgoExpert challenges?

**Comment by pinglu85** [comment]
Hi,
this repo is kind of like my personal blog where I write down approaches and solutions to AlgoExpert questions that I solved. This process helps me learn the patterns and the logic in a algorithm better. So this repo doesn't accept any contribution of solutions.

**Comment by Phakeme** [comment]
I see, thanks man great work.

**Comment by pinglu85** [comment]
Thanks.
